In [1]:
import numpy as np
mylist = [1,2,3]
myarray = np.array(mylist)
print(myarray.shape)

(3,)


In [2]:
myarray = np.array([[1,2,3],[4,5,6]])
print(myarray[0])


[1 2 3]


In [3]:
print(myarray[0][1])

2


In [4]:
print(myarray[0,1])

2


In [5]:
print(myarray[:])


[[1 2 3]
 [4 5 6]]


In [6]:
print(myarray[:,1:3])

[[2 3]
 [5 6]]


In [7]:
print(myarray[:,2])


[3 6]


In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [9]:
print(a + b)

[5 7 9]


In [10]:
a = np.array([1,2])


In [11]:
print(a + b)

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [12]:
a = np.array([1,2,3])


In [13]:
print(a + b)

[5 7 9]


In [14]:
print(a*b)

[ 4 10 18]


In [15]:
c = a.dot(b)
print(c)

32


In [16]:
print(np.dot(a,b))


32


In [17]:
print(a@b)

32


In [18]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[4,5],[7,8]])
print(a.shape)
print(b.shape)
print(np.dot(a,b).shape)

(2, 3)
(3, 2)
(2, 2)


In [19]:
a = np.array([1,2,3])
b = np.array([1,2,3])
print(a.shape)
print(b.shape)
print(np.dot(a,b).shape)

(3,)
(3,)
()


In [20]:
print(np.dot(a,b))

14
