In [22]:
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest
from sklearn.decomposition import PCA
import pandas as pd
import numpy

In [9]:
filename = 'diabetes.csv'
names =['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataset_dataframe = pd.read_csv(filename, names = names)
print(dataset_dataframe.head(5))

   preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1


In [15]:
dataset_array = dataset_dataframe.to_numpy()
x = dataset_array[:, 0:8]
y = dataset_array[:, 8]



In [19]:
test = SelectKBest(score_func = chi2, k = 4)
fit = test.fit(x, y)
selected_features = test.transform(x) 
print(selected_features)


[[148.    0.   33.6  50. ]
 [ 85.    0.   26.6  31. ]
 [183.    0.   23.3  32. ]
 ...
 [121.  112.   26.2  30. ]
 [126.    0.   30.1  47. ]
 [ 93.    0.   30.4  23. ]]


In [36]:
pca = PCA(n_components=3)
pca_components = pca.fit_transform(x)
print(pca_components)

[[-75.71465491 -35.95078264  -7.26078895]
 [-82.3582676   28.90821322  -5.49667139]
 [-74.63064344 -67.90649647  19.46180812]
 ...
 [ 32.11319827   3.3766648   -1.58786446]
 [-80.21449431 -14.18601977  12.3512639 ]
 [-81.30814972  21.62149606  -8.15276833]]
