In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../datasets/wine.csv', sep=';')

In [3]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [4]:
corr_matrix = df.corr()
corr_matrix['quality'].sort_values(ascending = False)


quality                 1.000000
alcohol                 0.476166
sulphates               0.251397
citric acid             0.226373
fixed acidity           0.124052
residual sugar          0.013732
free sulfur dioxide    -0.050656
pH                     -0.057731
chlorides              -0.128907
density                -0.174919
total sulfur dioxide   -0.185100
volatile acidity       -0.390558
Name: quality, dtype: float64

In [5]:
x = df.drop(['quality'], axis = 1)
y = df['quality'].copy()

In [6]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(df,test_size = 0.2, random_state = 5)



In [7]:
from sklearn.preprocessing import StandardScaler
import numpy as np

x = train.drop(labels = ['quality'], axis = 1)
y = train['quality'].copy()

from sklearn.decomposition import PCA

train_y = np.array(y)

In [8]:
from sklearn.pipeline import Pipeline
our_pipeline = Pipeline([('standardization', StandardScaler()), ('pca', PCA())])
train_x = our_pipeline.fit_transform(x)

In [9]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(train_x, train_y)

LinearRegression()

In [10]:
data_labels = np.array(test['quality'].copy())
data = test.drop(labels = ['quality'],axis = 1)

data = our_pipeline.fit_transform(data)

In [11]:
predicted_values = model.predict(data)


In [12]:
from sklearn.metrics import mean_squared_error

error = mean_squared_error(predicted_values, data_labels)

In [13]:
error

0.523352478110773

In [14]:
print('linear model performance',model.score(data, data_labels))

linear model performance 0.19357017893998718


In [15]:
from sklearn.tree import DecisionTreeRegressor
dmodel = DecisionTreeRegressor()
dmodel.fit(train_x, train_y)

DecisionTreeRegressor()

In [16]:
error = mean_squared_error(dmodel.predict(data), data_labels)

In [17]:
error

0.88125

In [278]:
from sklearn.model_selection import cross_val_score 
scores = cross_val_score(dmodel, train_x, train_y, scoring = 'neg_mean_squared_error')
scores

array([-0.6875    , -0.65234375, -0.61328125, -0.671875  , -0.76862745])

In [279]:
scores = np.sqrt(-scores)

In [280]:
scores.mean()

0.8232701549974337

In [281]:
from sklearn.ensemble import RandomForestRegressor
rmodel = RandomForestRegressor()
rmodel.fit(train_x, train_y)


RandomForestRegressor()

In [289]:
train_x.dtypes

AttributeError: 'numpy.ndarray' object has no attribute 'dtypes'

In [285]:
scores = cross_val_score(rmodel, train_x, train_y, scoring='accuracy')

C:\Users\Asus\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sklearn\model_selection\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sklearn\model_selection\_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sklearn\metrics\_scorer.py", line 103, in __call__
    score = scorer._score(cached_call, estimator, *args, **kwargs)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sklearn\metrics\_scorer.py", line 264, in _score
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sklearn\metrics\_classification.py", line 211, in ac

In [184]:
scores

array([0.44556465, 0.46122953, 0.38064234, 0.52652579, 0.426763  ])

In [185]:

scores.mean()

0.44814506058970033

In [186]:
rmodel.score(data, data_labels)

0.4761173124670829

In [188]:
from sklearn.linear_model import LogisticRegression
lmodel = LogisticRegression(random_state = 0, max_iter = 10000)
lmodel.fit(train_x, train_y)


LogisticRegression(max_iter=10000, random_state=0)

In [189]:
score = cross_val_score(lmodel, train_x, train_y)

In [190]:
score


array([0.61328125, 0.58984375, 0.5390625 , 0.6171875 , 0.55294118])

In [191]:
score.mean()

0.5824632352941176

In [261]:
import random
index = random.randrange(len(data))

prediction = np.mean([model.predict([data[index]]),rmodel.predict([data[index]]),dmodel.predict([data[index]])
                       , lmodel.predict([data[index]])])
print(prediction, data_labels[index])

5.100753408931361 5
